# Generated by Django 5.2.5 on 2025-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(max_length=30)),
                ('Destination', models.CharField(max_length=30)),
                ('Distance', models.IntegerField(max_length=20)),
            ],
        ),
    ]
