# Generated by Django 5.2.5 on 2025-08-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='Distance',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='Origin',
            new_name='origin',
        ),
    ]
