# Generated by Django 5.2.5 on 2025-08-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='assigned_vehicle',
            new_name='vehicle',
        ),
    ]
