# Generated by Django 5.2.5 on 2025-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_rename_assigned_vehicle_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
