# Generated by Django 5.2.5 on 2025-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('product_description', models.CharField(db_column='product_description', max_length=100)),
                ('weight_kg', models.FloatField(db_column='weight_kg')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
