# Generated by Django 5.2.5 on 2025-08-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('invoice', '0001_initial'),
        ('product', '0001_initial'),
        ('route', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('weight', models.FloatField()),
                ('Fuel_used', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='invoice.invoice')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
