# Generated by Django 5.2.5 on 2025-08-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('product', '0001_initial'),
        ('route', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('standard_charge', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('fuel_used', models.FloatField()),
                ('dnote_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnote_no', models.CharField(max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='trips.trips')),
            ],
        ),
    ]
