# Generated by Django 5.2.5 on 2025-08-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='weight',
            new_name='weight_kg',
        ),
        migrations.DeleteModel(
            name='DeliveryNote',
        ),
    ]
