# Generated by Django 5.2.5 on 2025-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trips_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
