# Generated by Django 5.2.5 on 2025-08-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('trips', '0005_remove_trips_driver_trips_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='drivers',
        ),
        migrations.AddField(
            model_name='trips',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
