# Generated by Django 5.2.5 on 2025-08-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('dispatcher', 'Dispatcher')], default='driver', max_length=20),
        ),
    ]
