# Generated by Django 5.2.5 on 2025-08-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('DNote_no', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subtotal', models.FloatField()),
                ('tax', models.FloatField()),
                ('Total', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
