# Generated by Django 5.2.5 on 2025-08-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Total',
            new_name='total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
