# Generated by Django 5.2.5 on 2025-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='trips',
        ),
        migrations.AddField(
            model_name='invoice',
            name='trips',
            field=models.ManyToManyField(related_name='invoices', to='trips.trips'),
        ),
    ]
