# Generated by Django 5.2.5 on 2025-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('efficiency', models.FloatField(help_text='km per litre')),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('tonnage', models.IntegerField(choices=[(1, '1 ton'), (2, '2 tons'), (3, '3 tons'), (4, '4 tons'), (5, '5 tons'), (6, '6 tons'), (7, '7 tons'), (8, '8 tons'), (9, '9 tons'), (10, '10 tons'), (12, '12 tons'), (15, '15 tons'), (20, '20 tons'), (28, '28 tons'), (30, '30 tons')], default=1, help_text='Vehicle weight')),
            ],
        ),
    ]
