# Generated by Django 5.2.5 on 2025-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='efficiency',
            field=models.FloatField(default=0.0, help_text='km per litre'),
        ),
    ]
